import pandas as pd
import argparse
from sklearn.cluster import KMeans
import numpy as np
import matplotlib.pyplot as plt
from sklearn.metrics import silhouette_score

# Load the data
def load_data(path: str) -> pd.DataFrame:
    # Load and transpose
    df = pd.read_csv(path).T

    # Make sure column names are species
    df = df.rename(columns=df.iloc[0])
    df = df.drop("Supplemental Table S3.  Species-level OTU table generated by MetaPhlAn2 analysis. Sample numbers in red correspond to the caries group and sample numbers in black correspond to the healthy group.")
    df = df.reset_index(drop=True)
    
    # Rename sampleID column
    df = df.rename(columns={"species":"sampleID"})

    return df

def extract_numpy(df: pd.DataFrame, norm:bool = True) -> np.array:
    normalized_data = df.drop(columns=["sampleID"]).astype(float)
    
    if norm:
        normalized_data = normalized_data.div(normalized_data.sum(axis=1), axis=0)
        normalized_data[normalized_data.isnull()] = 1.0e-5
        normalized_data[normalized_data.eq(0)] = 1.0e-5

    return normalized_data.to_numpy()

def print_elbow(data: np.array, n: int):
    inertias = []
    for n_clusters in range(1,n):
        kmeans = KMeans(n_clusters=n_clusters)
        kmeans.fit(data)
        inertias.append(-kmeans.score(data))

    plt.plot(range(1,n), inertias)
    plt.savefig("elbow.jpeg")
    plt.clf()

def print_silhouettes(data: np.array, n: int):
    scores = []
    for n_clusters in range(2,n):
        kmeans = KMeans(n_clusters=n_clusters)
        kmeans.fit(data)
        scores.append(silhouette_score(data, kmeans.labels_))

    plt.plot(range(2,n), scores)
    plt.savefig("silhouette.jpeg")
    plt.clf()

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Trains or uses a neural network classifier on microbiome count data")

    # Arguments for tool
    arguments = parser.add_argument_group("Arguments")
    arguments.add_argument("-in", "--input", help="Path to train input data as csv", default=None, required = True)
    arguments.add_argument("-out", "--output", help="Path to train input data as csv", default=None, required = True)
    arguments.add_argument("-cl", "--clusters", type=int, help="Number of clusters to use", default=None)
    arguments.add_argument("-gr", "--graph", action=argparse.BooleanOptionalAction, help="Generate graphs of sihlouette and inertia scores", default=False)
    args = parser.parse_args()

    path = args.input
    out = args.output

    df = load_data(path)

    # Normalize data
    data = extract_numpy(df, norm = True)
    print(data)
    
    if args.graph:
        print_elbow(data, 10)
        print_silhouettes(data, 10)
        exit(0)

    if args.clusters == None:
        print("ERROR: --clusters <int> required for clustering")
        exit(1)

    kmeans = KMeans(n_clusters=args.clusters)
    predictions = kmeans.fit_predict(data)

    unique_csts = [f"CST{i}" for i in range(args.clusters)]
    df["HC_subCST"] = list(map(lambda x:unique_csts[x], predictions))

    df.to_csv(out)
